apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-service-deployment
  labels:
    app: server-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server-service
  template:
    metadata:
      labels:
        app: server-service
    spec:
      containers:
        - name: server-service
          image: ninucabas/microservice:server
          ports:
            - containerPort: 3000
